services:
  runpod-proxy:
    build: .
    container_name: runpod-serverless-proxy
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - ai-queue-master_default

networks:
  default:
  ai-queue-master_default:
    external: true
